version: '2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.2.1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.2.1
    ports:
      - 5601:5601
    environment:
      - SERVER_NAME=[server_IP_here]:5601
      - ELASTICSEARCH_URL=http://[server_IP_here]:9200
